In [22]:
import pandas as pd
import numpy as np

np.random.seed(42)

In [23]:
# skapa först 100 kunder
number_of_customers = 10000

#skapa tom lista för att spara kund:id
customer_ids = []

# gå igenom kundnummer 1 till 100
for customer_number in range(1, number_of_customers + 1):

 # skapa ett kundID, exempelvis C00001
 customer_id = f"C{customer_number:05d}"
 # lägg in IDt i listan
 customer_ids.append(customer_id)

print(customer_ids)

['C00001', 'C00002', 'C00003', 'C00004', 'C00005', 'C00006', 'C00007', 'C00008', 'C00009', 'C00010', 'C00011', 'C00012', 'C00013', 'C00014', 'C00015', 'C00016', 'C00017', 'C00018', 'C00019', 'C00020', 'C00021', 'C00022', 'C00023', 'C00024', 'C00025', 'C00026', 'C00027', 'C00028', 'C00029', 'C00030', 'C00031', 'C00032', 'C00033', 'C00034', 'C00035', 'C00036', 'C00037', 'C00038', 'C00039', 'C00040', 'C00041', 'C00042', 'C00043', 'C00044', 'C00045', 'C00046', 'C00047', 'C00048', 'C00049', 'C00050', 'C00051', 'C00052', 'C00053', 'C00054', 'C00055', 'C00056', 'C00057', 'C00058', 'C00059', 'C00060', 'C00061', 'C00062', 'C00063', 'C00064', 'C00065', 'C00066', 'C00067', 'C00068', 'C00069', 'C00070', 'C00071', 'C00072', 'C00073', 'C00074', 'C00075', 'C00076', 'C00077', 'C00078', 'C00079', 'C00080', 'C00081', 'C00082', 'C00083', 'C00084', 'C00085', 'C00086', 'C00087', 'C00088', 'C00089', 'C00090', 'C00091', 'C00092', 'C00093', 'C00094', 'C00095', 'C00096', 'C00097', 'C00098', 'C00099', 'C00100', 'C00101', 'C00102', 'C00103', 'C00104', 'C00105', 'C00106', 'C00107', 'C00108', 'C00109', 'C00110', 'C00111', 'C00112', 'C00113', 'C00114', 'C00115', 'C00116', 'C00117', 'C00118', 'C00119', 'C00120', 'C00121', 'C00122', 'C00123', 'C00124', 'C00125', 'C00126', 'C00127', 'C00128', 'C00129', 'C00130', 'C00131', 'C00132', 'C00133', 'C00134', 'C00135', 'C00136', 'C00137', 'C00138', 'C00139', 'C00140', 'C00141', 'C00142', 'C00143', 'C00144', 'C00145', 'C00146', 'C00147', 'C00148', 'C00149', 'C00150', 'C00151', 'C00152', 'C00153', 'C00154', 'C00155', 'C00156', 'C00157', 'C00158', 'C00159', 'C00160', 'C00161', 'C00162', 'C00163', 'C00164', 'C00165', 'C00166', 'C00167', 'C00168', 'C00169', 'C00170', 'C00171', 'C00172', 'C00173', 'C00174', 'C00175', 'C00176', 'C00177', 'C00178', 'C00179', 'C00180', 'C00181', 'C00182', 'C00183', 'C00184', 'C00185', 'C00186', 'C00187', 'C00188', 'C00189', 'C00190', 'C00191', 'C00192', 'C00193', 'C00194', 'C00195', 'C00196', 'C00197', 'C00198', 'C00199', 'C00200', 'C00201', 'C00202', 'C00203', 'C00204', 'C00205', 'C00206', 'C00207', 'C00208', 'C00209', 'C00210', 'C00211', 'C00212', 'C00213', 'C00214', 'C00215', 'C00216', 'C00217', 'C00218', 'C00219', 'C00220', 'C00221', 'C00222', 'C00223', 'C00224', 'C00225', 'C00226', 'C00227', 'C00228', 'C00229', 'C00230', 'C00231', 'C00232', 'C00233', 'C00234', 'C00235', 'C00236', 'C00237', 'C00238', 'C00239', 'C00240', 'C00241', 'C00242', 'C00243', 'C00244', 'C00245', 'C00246', 'C00247', 'C00248', 'C00249', 'C00250', 'C00251', 'C00252', 'C00253', 'C00254', 'C00255', 'C00256', 'C00257', 'C00258', 'C00259', 'C00260', 'C00261', 'C00262', 'C00263', 'C00264', 'C00265', 'C00266', 'C00267', 'C00268', 'C00269', 'C00270', 'C00271', 'C00272', 'C00273', 'C00274', 'C00275', 'C00276', 'C00277', 'C00278', 'C00279', 'C00280', 'C00281', 'C00282', 'C00283', 'C00284', 'C00285', 'C00286', 'C00287', 'C00288', 'C00289', 'C00290', 'C00291', 'C00292', 'C00293', 'C00294', 'C00295', 'C00296', 'C00297', 'C00298', 'C00299', 'C00300', 'C00301', 'C00302', 'C00303', 'C00304', 'C00305', 'C00306', 'C00307', 'C00308', 'C00309', 'C00310', 'C00311', 'C00312', 'C00313', 'C00314', 'C00315', 'C00316', 'C00317', 'C00318', 'C00319', 'C00320', 'C00321', 'C00322', 'C00323', 'C00324', 'C00325', 'C00326', 'C00327', 'C00328', 'C00329', 'C00330', 'C00331', 'C00332', 'C00333', 'C00334', 'C00335', 'C00336', 'C00337', 'C00338', 'C00339', 'C00340', 'C00341', 'C00342', 'C00343', 'C00344', 'C00345', 'C00346', 'C00347', 'C00348', 'C00349', 'C00350', 'C00351', 'C00352', 'C00353', 'C00354', 'C00355', 'C00356', 'C00357', 'C00358', 'C00359', 'C00360', 'C00361', 'C00362', 'C00363', 'C00364', 'C00365', 'C00366', 'C00367', 'C00368', 'C00369', 'C00370', 'C00371', 'C00372', 'C00373', 'C00374', 'C00375', 'C00376', 'C00377', 'C00378', 'C00379', 'C00380', 'C00381', 'C00382', 'C00383', 'C00384', 'C00385', 'C00386', 'C00387', 'C00388', 'C00389', 'C00390', 'C00391', 'C00392', 'C00393', 'C00394', 'C00395', 'C00396', 'C00397', 'C00398', 'C00399', 'C00400', 'C00401', 'C00402', 'C00403', 'C00404', 'C00405', 'C00406', 'C00407', 'C00408', 'C00409', 'C00410', 'C00411', 'C00412', 'C00413', 'C00414', 'C00415', 'C00416', 'C00417', 'C00418', 'C00419', 'C00420', 'C00421', 'C00422', 'C00423', 'C00424', 'C00425', 'C00426', 'C00427', 'C00428', 'C00429', 'C00430', 'C00431', 'C00432', 'C00433', 'C00434', 'C00435', 'C00436', 'C00437', 'C00438', 'C00439', 'C00440', 'C00441', 'C00442', 'C00443', 'C00444', 'C00445', 'C00446', 'C00447', 'C00448', 'C00449', 'C00450', 'C00451', 'C00452', 'C00453', 'C00454', 'C00455', 'C00456', 'C00457', 'C00458', 'C00459', 'C00460', 'C00461', 'C00462', 'C00463', 'C00464', 'C00465', 'C00466', 'C00467', 'C00468', 'C00469', 'C00470', 'C00471', 'C00472', 'C00473', 'C00474', 'C00475', 'C00476', 'C00477', 'C00478', 'C00479', 'C00480', 'C00481', 'C00482', 'C00483', 'C00484', 'C00485', 'C00486', 'C00487', 'C00488', 'C00489', 'C00490', 'C00491', 'C00492', 'C00493', 'C00494', 'C00495', 'C00496', 'C00497', 'C00498', 'C00499', 'C00500', 'C00501', 'C00502', 'C00503', 'C00504', 'C00505', 'C00506', 'C00507', 'C00508', 'C00509', 'C00510', 'C00511', 'C00512', 'C00513', 'C00514', 'C00515', 'C00516', 'C00517', 'C00518', 'C00519', 'C00520', 'C00521', 'C00522', 'C00523', 'C00524', 'C00525', 'C00526', 'C00527', 'C00528', 'C00529', 'C00530', 'C00531', 'C00532', 'C00533', 'C00534', 'C00535', 'C00536', 'C00537', 'C00538', 'C00539', 'C00540', 'C00541', 'C00542', 'C00543', 'C00544', 'C00545', 'C00546', 'C00547', 'C00548', 'C00549', 'C00550', 'C00551', 'C00552', 'C00553', 'C00554', 'C00555', 'C00556', 'C00557', 'C00558', 'C00559', 'C00560', 'C00561', 'C00562', 'C00563', 'C00564', 'C00565', 'C00566', 'C00567', 'C00568', 'C00569', 'C00570', 'C00571', 'C00572', 'C00573', 'C00574', 'C00575', 'C00576', 'C00577', 'C00578', 'C00579', 'C00580', 'C00581', 'C00582', 'C00583', 'C00584', 'C00585', 'C00586', 'C00587', 'C00588', 'C00589', 'C00590', 'C00591', 'C00592', 'C00593', 'C00594', 'C00595', 'C00596', 'C00597', 'C00598', 'C00599', 'C00600', 'C00601', 'C00602', 'C00603', 'C00604', 'C00605', 'C00606', 'C00607', 'C00608', 'C00609', 'C00610', 'C00611', 'C00612', 'C00613', 'C00614', 'C00615', 'C00616', 'C00617', 'C00618', 'C00619', 'C00620', 'C00621', 'C00622', 'C00623', 'C00624', 'C00625', 'C00626', 'C00627', 'C00628', 'C00629', 'C00630', 'C00631', 'C00632', 'C00633', 'C00634', 'C00635', 'C00636', 'C00637', 'C00638', 'C00639', 'C00640', 'C00641', 'C00642', 'C00643', 'C00644', 'C00645', 'C00646', 'C00647', 'C00648', 'C00649', 'C00650', 'C00651', 'C00652', 'C00653', 'C00654', 'C00655', 'C00656', 'C00657', 'C00658', 'C00659', 'C00660', 'C00661', 'C00662', 'C00663', 'C00664', 'C00665', 'C00666', 'C00667', 'C00668', 'C00669', 'C00670', 'C00671', 'C00672', 'C00673', 'C00674', 'C00675', 'C00676', 'C00677', 'C00678', 'C00679', 'C00680', 'C00681', 'C00682', 'C00683', 'C00684', 'C00685', 'C00686', 'C00687', 'C00688', 'C00689', 'C00690', 'C00691', 'C00692', 'C00693', 'C00694', 'C00695', 'C00696', 'C00697', 'C00698', 'C00699', 'C00700', 'C00701', 'C00702', 'C00703', 'C00704', 'C00705', 'C00706', 'C00707', 'C00708', 'C00709', 'C00710', 'C00711', 'C00712', 'C00713', 'C00714', 'C00715', 'C00716', 'C00717', 'C00718', 'C00719', 'C00720', 'C00721', 'C00722', 'C00723', 'C00724', 'C00725', 'C00726', 'C00727', 'C00728', 'C00729', 'C00730', 'C00731', 'C00732', 'C00733', 'C00734', 'C00735', 'C00736', 'C00737', 'C00738', 'C00739', 'C00740', 'C00741', 'C00742', 'C00743', 'C00744', 'C00745', 'C00746', 'C00747', 'C00748', 'C00749', 'C00750', 'C00751', 'C00752', 'C00753', 'C00754', 'C00755', 'C00756', 'C00757', 'C00758', 'C00759', 'C00760', 'C00761', 'C00762', 'C00763', 'C00764', 'C00765', 'C00766', 'C00767', 'C00768', 'C00769', 'C00770', 'C00771', 'C00772', 'C00773', 'C00774', 'C00775', 'C00776', 'C00777', 'C00778', 'C00779', 'C00780', 'C00781', 'C00782', 'C00783', 'C00784', 'C00785', 'C00786', 'C00787', 'C00788', 'C00789', 'C00790', 'C00791', 'C00792', 'C00793', 'C00794', 'C00795', 'C00796', 'C00797', 'C00798', 'C00799', 'C00800', 'C00801', 'C00802', 'C00803', 'C00804', 'C00805', 'C00806', 'C00807', 'C00808', 'C00809', 'C00810', 'C00811', 'C00812', 'C00813', 'C00814', 'C00815', 'C00816', 'C00817', 'C00818', 'C00819', 'C00820', 'C00821', 'C00822', 'C00823', 'C00824', 'C00825', 'C00826', 'C00827', 'C00828', 'C00829', 'C00830', 'C00831', 'C00832', 'C00833', 'C00834', 'C00835', 'C00836', 'C00837', 'C00838', 'C00839', 'C00840', 'C00841', 'C00842', 'C00843', 'C00844', 'C00845', 'C00846', 'C00847', 'C00848', 'C00849', 'C00850', 'C00851', 'C00852', 'C00853', 'C00854', 'C00855', 'C00856', 'C00857', 'C00858', 'C00859', 'C00860', 'C00861', 'C00862', 'C00863', 'C00864', 'C00865', 'C00866', 'C00867', 'C00868', 'C00869', 'C00870', 'C00871', 'C00872', 'C00873', 'C00874', 'C00875', 'C00876', 'C00877', 'C00878', 'C00879', 'C00880', 'C00881', 'C00882', 'C00883', 'C00884', 'C00885', 'C00886', 'C00887', 'C00888', 'C00889', 'C00890', 'C00891', 'C00892', 'C00893', 'C00894', 'C00895', 'C00896', 'C00897', 'C00898', 'C00899', 'C00900', 'C00901', 'C00902', 'C00903', 'C00904', 'C00905', 'C00906', 'C00907', 'C00908', 'C00909', 'C00910', 'C00911', 'C00912', 'C00913', 'C00914', 'C00915', 'C00916', 'C00917', 'C00918', 'C00919', 'C00920', 'C00921', 'C00922', 'C00923', 'C00924', 'C00925', 'C00926', 'C00927', 'C00928', 'C00929', 'C00930', 'C00931', 'C00932', 'C00933', 'C00934', 'C00935', 'C00936', 'C00937', 'C00938', 'C00939', 'C00940', 'C00941', 'C00942', 'C00943', 'C00944', 'C00945', 'C00946', 'C00947', 'C00948', 'C00949', 'C00950', 'C00951', 'C00952', 'C00953', 'C00954', 'C00955', 'C00956', 'C00957', 'C00958', 'C00959', 'C00960', 'C00961', 'C00962', 'C00963', 'C00964', 'C00965', 'C00966', 'C00967', 'C00968', 'C00969', 'C00970', 'C00971', 'C00972', 'C00973', 'C00974', 'C00975', 'C00976', 'C00977', 'C00978', 'C00979', 'C00980', 'C00981', 'C00982', 'C00983', 'C00984', 'C00985', 'C00986', 'C00987', 'C00988', 'C00989', 'C00990', 'C00991', 'C00992', 'C00993', 'C00994', 'C00995', 'C00996', 'C00997', 'C00998', 'C00999', 'C01000', 'C01001', 'C01002', 'C01003', 'C01004', 'C01005', 'C01006', 'C01007', 'C01008', 'C01009', 'C01010', 'C01011', 'C01012', 'C01013', 'C01014', 'C01015', 'C01016', 'C01017', 'C01018', 'C01019', 'C01020', 'C01021', 'C01022', 'C01023', 'C01024', 'C01025', 'C01026', 'C01027', 'C01028', 'C01029', 'C01030', 'C01031', 'C01032', 'C01033', 'C01034', 'C01035', 'C01036', 'C01037', 'C01038', 'C01039', 'C01040', 'C01041', 'C01042', 'C01043', 'C01044', 'C01045', 'C01046', 'C01047', 'C01048', 'C01049', 'C01050', 'C01051', 'C01052', 'C01053', 'C01054', 'C01055', 'C01056', 'C01057', 'C01058', 'C01059', 'C01060', 'C01061', 'C01062', 'C01063', 'C01064', 'C01065', 'C01066', 'C01067', 'C01068', 'C01069', 'C01070', 'C01071', 'C01072', 'C01073', 'C01074', 'C01075', 'C01076', 'C01077', 'C01078', 'C01079', 'C01080', 'C01081', 'C01082', 'C01083', 'C01084', 'C01085', 'C01086', 'C01087', 'C01088', 'C01089', 'C01090', 'C01091', 'C01092', 'C01093', 'C01094', 'C01095', 'C01096', 'C01097', 'C01098', 'C01099', 'C01100', 'C01101', 'C01102', 'C01103', 'C01104', 'C01105', 'C01106', 'C01107', 'C01108', 'C01109', 'C01110', 'C01111', 'C01112', 'C01113', 'C01114', 'C01115', 'C01116', 'C01117', 'C01118', 'C01119', 'C01120', 'C01121', 'C01122', 'C01123', 'C01124', 'C01125', 'C01126', 'C01127', 'C01128', 'C01129', 'C01130', 'C01131', 'C01132', 'C01133', 'C01134', 'C01135', 'C01136', 'C01137', 'C01138', 'C01139', 'C01140', 'C01141', 'C01142', 'C01143', 'C01144', 'C01145', 'C01146', 'C01147', 'C01148', 'C01149', 'C01150', 'C01151', 'C01152', 'C01153', 'C01154', 'C01155', 'C01156', 'C01157', 'C01158', 'C01159', 'C01160', 'C01161', 'C01162', 'C01163', 'C01164', 'C01165', 'C01166', 'C01167', 'C01168', 'C01169', 'C01170', 'C01171', 'C01172', 'C01173', 'C01174', 'C01175', 'C01176', 'C01177', 'C01178', 'C01179', 'C01180', 'C01181', 'C01182', 'C01183', 'C01184', 'C01185', 'C01186', 'C01187', 'C01188', 'C01189', 'C01190', 'C01191', 'C01192', 'C01193', 'C01194', 'C01195', 'C01196', 'C01197', 'C01198', 'C01199', 'C01200', 'C01201', 'C01202', 'C01203', 'C01204', 'C01205', 'C01206', 'C01207', 'C01208', 'C01209', 'C01210', 'C01211', 'C01212', 'C01213', 'C01214', 'C01215', 'C01216', 'C01217', 'C01218', 'C01219', 'C01220', 'C01221', 'C01222', 'C01223', 'C01224', 'C01225', 'C01226', 'C01227', 'C01228', 'C01229', 'C01230', 'C01231', 'C01232', 'C01233', 'C01234', 'C01235', 'C01236', 'C01237', 'C01238', 'C01239', 'C01240', 'C01241', 'C01242', 'C01243', 'C01244', 'C01245', 'C01246', 'C01247', 'C01248', 'C01249', 'C01250', 'C01251', 'C01252', 'C01253', 'C01254', 'C01255', 'C01256', 'C01257', 'C01258', 'C01259', 'C01260', 'C01261', 'C01262', 'C01263', 'C01264', 'C01265', 'C01266', 'C01267', 'C01268', 'C01269', 'C01270', 'C01271', 'C01272', 'C01273', 'C01274', 'C01275', 'C01276', 'C01277', 'C01278', 'C01279', 'C01280', 'C01281', 'C01282', 'C01283', 'C01284', 'C01285', 'C01286', 'C01287', 'C01288', 'C01289', 'C01290', 'C01291', 'C01292', 'C01293', 'C01294', 'C01295', 'C01296', 'C01297', 'C01298', 'C01299', 'C01300', 'C01301', 'C01302', 'C01303', 'C01304', 'C01305', 'C01306', 'C01307', 'C01308', 'C01309', 'C01310', 'C01311', 'C01312', 'C01313', 'C01314', 'C01315', 'C01316', 'C01317', 'C01318', 'C01319', 'C01320', 'C01321', 'C01322', 'C01323', 'C01324', 'C01325', 'C01326', 'C01327', 'C01328', 'C01329', 'C01330', 'C01331', 'C01332', 'C01333', 'C01334', 'C01335', 'C01336', 'C01337', 'C01338', 'C01339', 'C01340', 'C01341', 'C01342', 'C01343', 'C01344', 'C01345', 'C01346', 'C01347', 'C01348', 'C01349', 'C01350', 'C01351', 'C01352', 'C01353', 'C01354', 'C01355', 'C01356', 'C01357', 'C01358', 'C01359', 'C01360', 'C01361', 'C01362', 'C01363', 'C01364', 'C01365', 'C01366', 'C01367', 'C01368', 'C01369', 'C01370', 'C01371', 'C01372', 'C01373', 'C01374', 'C01375', 'C01376', 'C01377', 'C01378', 'C01379', 'C01380', 'C01381', 'C01382', 'C01383', 'C01384', 'C01385', 'C01386', 'C01387', 'C01388', 'C01389', 'C01390', 'C01391', 'C01392', 'C01393', 'C01394', 'C01395', 'C01396', 'C01397', 'C01398', 'C01399', 'C01400', 'C01401', 'C01402', 'C01403', 'C01404', 'C01405', 'C01406', 'C01407', 'C01408', 'C01409', 'C01410', 'C01411', 'C01412', 'C01413', 'C01414', 'C01415', 'C01416', 'C01417', 'C01418', 'C01419', 'C01420', 'C01421', 'C01422', 'C01423', 'C01424', 'C01425', 'C01426', 'C01427', 'C01428', 'C01429', 'C01430', 'C01431', 'C01432', 'C01433', 'C01434', 'C01435', 'C01436', 'C01437', 'C01438', 'C01439', 'C01440', 'C01441', 'C01442', 'C01443', 'C01444', 'C01445', 'C01446', 'C01447', 'C01448', 'C01449', 'C01450', 'C01451', 'C01452', 'C01453', 'C01454', 'C01455', 'C01456', 'C01457', 'C01458', 'C01459', 'C01460', 'C01461', 'C01462', 'C01463', 'C01464', 'C01465', 'C01466', 'C01467', 'C01468', 'C01469', 'C01470', 'C01471', 'C01472', 'C01473', 'C01474', 'C01475', 'C01476', 'C01477', 'C01478', 'C01479', 'C01480', 'C01481', 'C01482', 'C01483', 'C01484', 'C01485', 'C01486', 'C01487', 'C01488', 'C01489', 'C01490', 'C01491', 'C01492', 'C01493', 'C01494', 'C01495', 'C01496', 'C01497', 'C01498', 'C01499', 'C01500', 'C01501', 'C01502', 'C01503', 'C01504', 'C01505', 'C01506', 'C01507', 'C01508', 'C01509', 'C01510', 'C01511', 'C01512', 'C01513', 'C01514', 'C01515', 'C01516', 'C01517', 'C01518', 'C01519', 'C01520', 'C01521', 'C01522', 'C01523', 'C01524', 'C01525', 'C01526', 'C01527', 'C01528', 'C01529', 'C01530', 'C01531', 'C01532', 'C01533', 'C01534', 'C01535', 'C01536', 'C01537', 'C01538', 'C01539', 'C01540', 'C01541', 'C01542', 'C01543', 'C01544', 'C01545', 'C01546', 'C01547', 'C01548', 'C01549', 'C01550', 'C01551', 'C01552', 'C01553', 'C01554', 'C01555', 'C01556', 'C01557', 'C01558', 'C01559', 'C01560', 'C01561', 'C01562', 'C01563', 'C01564', 'C01565', 'C01566', 'C01567', 'C01568', 'C01569', 'C01570', 'C01571', 'C01572', 'C01573', 'C01574', 'C01575', 'C01576', 'C01577', 'C01578', 'C01579', 'C01580', 'C01581', 'C01582', 'C01583', 'C01584', 'C01585', 'C01586', 'C01587', 'C01588', 'C01589', 'C01590', 'C01591', 'C01592', 'C01593', 'C01594', 'C01595', 'C01596', 'C01597', 'C01598', 'C01599', 'C01600', 'C01601', 'C01602', 'C01603', 'C01604', 'C01605', 'C01606', 'C01607', 'C01608', 'C01609', 'C01610', 'C01611', 'C01612', 'C01613', 'C01614', 'C01615', 'C01616', 'C01617', 'C01618', 'C01619', 'C01620', 'C01621', 'C01622', 'C01623', 'C01624', 'C01625', 'C01626', 'C01627', 'C01628', 'C01629', 'C01630', 'C01631', 'C01632', 'C01633', 'C01634', 'C01635', 'C01636', 'C01637', 'C01638', 'C01639', 'C01640', 'C01641', 'C01642', 'C01643', 'C01644', 'C01645', 'C01646', 'C01647', 'C01648', 'C01649', 'C01650', 'C01651', 'C01652', 'C01653', 'C01654', 'C01655', 'C01656', 'C01657', 'C01658', 'C01659', 'C01660', 'C01661', 'C01662', 'C01663', 'C01664', 'C01665', 'C01666', 'C01667', 'C01668', 'C01669', 'C01670', 'C01671', 'C01672', 'C01673', 'C01674', 'C01675', 'C01676', 'C01677', 'C01678', 'C01679', 'C01680', 'C01681', 'C01682', 'C01683', 'C01684', 'C01685', 'C01686', 'C01687', 'C01688', 'C01689', 'C01690', 'C01691', 'C01692', 'C01693', 'C01694', 'C01695', 'C01696', 'C01697', 'C01698', 'C01699', 'C01700', 'C01701', 'C01702', 'C01703', 'C01704', 'C01705', 'C01706', 'C01707', 'C01708', 'C01709', 'C01710', 'C01711', 'C01712', 'C01713', 'C01714', 'C01715', 'C01716', 'C01717', 'C01718', 'C01719', 'C01720', 'C01721', 'C01722', 'C01723', 'C01724', 'C01725', 'C01726', 'C01727', 'C01728', 'C01729', 'C01730', 'C01731', 'C01732', 'C01733', 'C01734', 'C01735', 'C01736', 'C01737', 'C01738', 'C01739', 'C01740', 'C01741', 'C01742', 'C01743', 'C01744', 'C01745', 'C01746', 'C01747', 'C01748', 'C01749', 'C01750', 'C01751', 'C01752', 'C01753', 'C01754', 'C01755', 'C01756', 'C01757', 'C01758', 'C01759', 'C01760', 'C01761', 'C01762', 'C01763', 'C01764', 'C01765', 'C01766', 'C01767', 'C01768', 'C01769', 'C01770', 'C01771', 'C01772', 'C01773', 'C01774', 'C01775', 'C01776', 'C01777', 'C01778', 'C01779', 'C01780', 'C01781', 'C01782', 'C01783', 'C01784', 'C01785', 'C01786', 'C01787', 'C01788', 'C01789', 'C01790', 'C01791', 'C01792', 'C01793', 'C01794', 'C01795', 'C01796', 'C01797', 'C01798', 'C01799', 'C01800', 'C01801', 'C01802', 'C01803', 'C01804', 'C01805', 'C01806', 'C01807', 'C01808', 'C01809', 'C01810', 'C01811', 'C01812', 'C01813', 'C01814', 'C01815', 'C01816', 'C01817', 'C01818', 'C01819', 'C01820', 'C01821', 'C01822', 'C01823', 'C01824', 'C01825', 'C01826', 'C01827', 'C01828', 'C01829', 'C01830', 'C01831', 'C01832', 'C01833', 'C01834', 'C01835', 'C01836', 'C01837', 'C01838', 'C01839', 'C01840', 'C01841', 'C01842', 'C01843', 'C01844', 'C01845', 'C01846', 'C01847', 'C01848', 'C01849', 'C01850', 'C01851', 'C01852', 'C01853', 'C01854', 'C01855', 'C01856', 'C01857', 'C01858', 'C01859', 'C01860', 'C01861', 'C01862', 'C01863', 'C01864', 'C01865', 'C01866', 'C01867', 'C01868', 'C01869', 'C01870', 'C01871', 'C01872', 'C01873', 'C01874', 'C01875', 'C01876', 'C01877', 'C01878', 'C01879', 'C01880', 'C01881', 'C01882', 'C01883', 'C01884', 'C01885', 'C01886', 'C01887', 'C01888', 'C01889', 'C01890', 'C01891', 'C01892', 'C01893', 'C01894', 'C01895', 'C01896', 'C01897', 'C01898', 'C01899', 'C01900', 'C01901', 'C01902', 'C01903', 'C01904', 'C01905', 'C01906', 'C01907', 'C01908', 'C01909', 'C01910', 'C01911', 'C01912', 'C01913', 'C01914', 'C01915', 'C01916', 'C01917', 'C01918', 'C01919', 'C01920', 'C01921', 'C01922', 'C01923', 'C01924', 'C01925', 'C01926', 'C01927', 'C01928', 'C01929', 'C01930', 'C01931', 'C01932', 'C01933', 'C01934', 'C01935', 'C01936', 'C01937', 'C01938', 'C01939', 'C01940', 'C01941', 'C01942', 'C01943', 'C01944', 'C01945', 'C01946', 'C01947', 'C01948', 'C01949', 'C01950', 'C01951', 'C01952', 'C01953', 'C01954', 'C01955', 'C01956', 'C01957', 'C01958', 'C01959', 'C01960', 'C01961', 'C01962', 'C01963', 'C01964', 'C01965', 'C01966', 'C01967', 'C01968', 'C01969', 'C01970', 'C01971', 'C01972', 'C01973', 'C01974', 'C01975', 'C01976', 'C01977', 'C01978', 'C01979', 'C01980', 'C01981', 'C01982', 'C01983', 'C01984', 'C01985', 'C01986', 'C01987', 'C01988', 'C01989', 'C01990', 'C01991', 'C01992', 'C01993', 'C01994', 'C01995', 'C01996', 'C01997', 'C01998', 'C01999', 'C02000',

In [24]:
# Svenska åldersgrupper med befolkningsstorlek som vikt
age_groups = [
    (20, 24, 602823),
    (25, 34, 1363717),
    (35, 44, 1423815),
    (45, 54, 1306445),
    (55, 64, 1293429),
    (65, 79, 1551575)
]

# Hämta befolkningsstorleken från varje grupp
age_weights = []

for group in age_groups:
    age_weights.append(group[2])

# Gör om befolkningsstorlekarna till sannolikheter
age_probabilities = np.array(age_weights) / sum(age_weights)

# Välj först vilken åldersgrupp varje kund ska tillhöra
selected_age_groups = np.random.choice(
    len(age_groups),
    number_of_customers,
    p=age_probabilities
)

# Skapa sedan den exakta åldern
ages = []

for group_number in selected_age_groups:

    minimum_age = age_groups[group_number][0]
    maximum_age = age_groups[group_number][1]

    age = np.random.randint(minimum_age, maximum_age + 1)

    ages.append(age)

print(ages[:10])

[41, 68, 56, 49, 27, 33, 20, 67, 48, 63]

In [25]:
regions = [
    "Stockholms län",
    "Uppsala län",
    "Södermanlands län",
    "Östergötlands län",
    "Jönköpings län",
    "Kronobergs län",
    "Kalmar län",
    "Gotlands län",
    "Blekinge län",
    "Skåne län",
    "Hallands län",
    "Västra Götalands län",
    "Värmlands län",
    "Örebro län",
    "Västmanlands län",
    "Dalarnas län",
    "Gävleborgs län",
    "Västernorrlands län",
    "Jämtlands län",
    "Västerbottens län",
    "Norrbottens län"
]

region_populations = np.array([
    2486251,
    410575,
    300440,
    472529,
    369722,
    203121,
    245477,
    60852,
    156616,
    1433083,
    346090,
    1777803,
    283037,
    308357,
    280756,
    286043,
    283452,
    240640,
    132736,
    279028,
    248927
])

region_probabilities = region_populations / region_populations.sum()

customer_regions = np.random.choice(
    regions,
    number_of_customers,
    p=region_probabilities
)

print(customer_regions[:10])

['Stockholms län' 'Stockholms län' 'Dalarnas län' 'Västra Götalands län'
 'Östergötlands län' 'Skåne län' 'Stockholms län' 'Västra Götalands län'
 'Stockholms län' 'Västra Götalands län']

In [26]:
employment_statuses = [
    "Permanent employment",
    "Self-employed",
    "Temporary/Probation/Freelance",
    "Parental leave",
    "Student",
    "Unemployed",
    "Retired"
]

customer_employment_status = []

for age in ages:

    # Yngre kunder
    if age <= 24:

        probabilities = [
            0.30,  # Permanent employment
            0.03,  # Self-employed
            0.17,  # Temporary/Probation/Freelance
            0.01,  # Parental leave
            0.42,  # Student
            0.07,  # Unemployed
            0.00   # Retired
        ]

    # 25-34 år
    elif age <= 34:

        probabilities = [
            0.64,
            0.07,
            0.10,
            0.07,
            0.05,
            0.07,
            0.00
        ]

    # 35-54 år
    elif age <= 54:

        probabilities = [
            0.73,
            0.10,
            0.05,
            0.04,
            0.01,
            0.07,
            0.00
        ]

    # 55-62 år
    elif age <= 62:

        probabilities = [
            0.65,
            0.10,
            0.05,
            0.00,
            0.02,
            0.10,
            0.08
        ]

    # 63-66 år
    elif age <= 66:

        probabilities = [
            0.42,
            0.08,
            0.03,
            0.00,
            0.01,
            0.06,
            0.40
        ]

    # 67 år och äldre
    else:

        probabilities = [
            0.08,
            0.03,
            0.01,
            0.00,
            0.00,
            0.01,
            0.87
        ]

    employment_status = np.random.choice(
        employment_statuses,
        p=probabilities
    )

    customer_employment_status.append(employment_status)

print(customer_employment_status[:10])

[np.str_('Temporary/Probation/Freelance'), np.str_('Retired'), np.str_('Permanent employment'), np.str_('Permanent employment'), np.str_('Permanent employment'), np.str_('Self-employed'), np.str_('Self-employed'), np.str_('Retired'), np.str_('Permanent employment'), np.str_('Permanent employment')]

In [27]:
customer_monthly_income = []

for age, employment_status in zip(ages, customer_employment_status):

    if employment_status == "Permanent employment":

        if age <= 24:
            average_income = 30000
        elif age <= 34:
            average_income = 38000
        elif age <= 54:
            average_income = 45000
        else:
            average_income = 43000

        income = np.random.normal(average_income, 7000)
        income = np.clip(income, 22000, 90000)

    elif employment_status == "Self-employed":

        income = np.random.normal(45000, 18000)
        income = np.clip(income, 18000, 150000)

    elif employment_status == "Temporary/Probation/Freelance":

        income = np.random.normal(30000, 8000)
        income = np.clip(income, 15000, 60000)

    elif employment_status == "Parental leave":

        income = np.random.normal(30000, 6000)
        income = np.clip(income, 16000, 50000)

    elif employment_status == "Student":

        income = np.random.normal(10000, 5000)
        income = np.clip(income, 0, 25000)

    elif employment_status == "Unemployed":

        income = np.random.normal(14000, 4000)
        income = np.clip(income, 0, 25000)

    else:  # Retired

        income = np.random.normal(23900, 7000)
        income = np.clip(income, 12000, 60000)

    income = round(income / 100) * 100

    customer_monthly_income.append(int(income))

print(customer_monthly_income[:10])

[26400, 18900, 30800, 35700, 45900, 29900, 57100, 24000, 42600, 40000]

In [28]:
customers_df = pd.DataFrame({
    "customer_id": customer_ids,
    "age": ages,
    "region": customer_regions,
    "monthly_income": customer_monthly_income,
    "employment_status": customer_employment_status
})

customers_df.head(10)

,customer_id,age,region,monthly_income,employment_status
0,C00001,41,Stockholms län,26400,Temporary/Probation/Freelance
1,C00002,68,Stockholms län,18900,Retired
2,C00003,56,Dalarnas län,30800,Permanent employment
3,C00004,49,Västra Götalands län,35700,Permanent employment
4,C00005,27,Östergötlands län,45900,Permanent employment
5,C00006,33,Skåne län,29900,Self-employed
6,C00007,20,Stockholms län,57100,Self-employed
7,C00008,67,Västra Götalands län,24000,Retired
8,C00009,48,Stockholms län,42600,Permanent employment
9,C00010,63,Västra Götalands län,40000,Permanent employment

In [29]:
print("Antal kunder:", len(customers_df))

print("\nSaknade värden:")
print(customers_df.isna().sum())

print("\nSysselsättningsfördelning:")
print(customers_df["employment_status"].value_counts())

print("\nÅlder:")
print("Min:", customers_df["age"].min())
print("Max:", customers_df["age"].max())

print("\nInkomst:")
print("Min:", customers_df["monthly_income"].min())
print("Max:", customers_df["monthly_income"].max())
print("Medel:", round(customers_df["monthly_income"].mean()))

Antal kunder: 10000

Saknade värden:
customer_id          0
age                  0
region               0
monthly_income       0
employment_status    0
dtype: int64

Sysselsättningsfördelning:
employment_status
Permanent employment             5397
Retired                          1827
Self-employed                     759
Temporary/Probation/Freelance     618
Unemployed                        601
Student                           525
Parental leave                    273
Name: count, dtype: int64

Ålder:
Min: 20
Max: 79

Inkomst:
Min: 0
Max: 97500
Medel: 34744

In [30]:
print("Unika kund-ID:", customers_df["customer_id"].nunique())
print("Duplicerade kund-ID:", customers_df["customer_id"].duplicated().sum())

Unika kund-ID: 10000
Duplicerade kund-ID: 0

In [31]:
customers_df.groupby("employment_status")["monthly_income"].agg(
    ["count", "mean", "min", "max"]
).round(0)

                               count     mean    min    max
employment_status
Parental leave                   273  29787.0  16000  44300
Permanent employment            5397  42351.0  22000  72200
Retired                         1827  24079.0  12000  45700
Self-employed                    759  45404.0  18000  97500
Student                          525  10191.0      0  25000
Temporary/Probation/Freelance    618  30031.0  15000  54100
Unemployed                       601  13945.0   3700  25000

In [32]:
from pathlib import Path

project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

output_path = project_root / "data" / "customers.csv"

customers_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("CSV sparad här:")
print(output_path)

CSV sparad här:
c:\Users\ELIYA\Documents\nordic-credit-risk\data\customers.csv